version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
