version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase
  open-pull-requests-limit: 99

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
